github: Stop testing with Julia 1.6
The tests fail with:

    ERROR: The manifest file you are using was most likely generated
    by a different version of Julia and is not compatible with this
    Julia version

and I'm too lazy to figure out what's the cause.